# Generated by Django 3.2.9 on 2021-12-04 12:56

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='address',
            field=models.TextField(default='none', help_text='exihibition address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibition',
            name='end_date',
            field=django_jalali.db.models.jDateField(default='1400-1-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibition',
            name='start_date',
            field=django_jalali.db.models.jDateField(default='1400-1-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibition',
            name='title',
            field=models.TextField(default='no title', help_text='exhibition title'),
            preserve_default=False,
        ),
    ]
