# Generated by Django 3.2.9 on 2021-12-05 10:13

from django.db import migrations, models
import exhibitions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0002_auto_20211204_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('cellphone_number', models.CharField(max_length=11, validators=[exhibitions.validators.validate_cell_number])),
                ('phone_nunmber', models.CharField(blank=True, default='03100000000', max_length=11, validators=[exhibitions.validators.validate_phone_number])),
                ('subject', models.CharField(blank=True, default='Blank', max_length=50)),
                ('workplace', models.CharField(blank=True, default='Blank', max_length=50)),
                ('work_position', models.CharField(blank=True, default='Blank', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='exhibition',
            name='form_header',
            field=models.TextField(default='با تشکر از حضور جنابعالی در غرفه شرکت فنی مهندسی فناور پویا سپاهان. خواهشمند است نسبت به تکمیل فرم و اعلام درخواست اقدام فرمایید'),
        ),
    ]
