# Generated by Django 3.2.9 on 2021-12-05 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0003_auto_20211205_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='subject',
            new_name='expertise',
        ),
        migrations.AddField(
            model_name='visitor',
            name='coop_request',
            field=models.CharField(blank=True, choices=[('buy products', 'Buy Products'), ('sales branch', 'Sales Branch'), ('after sales branch', 'After Sale Branch'), (' get catalougue', 'Get Catalaougue'), ('presentation', 'Presentation'), ('not mentioned', 'Notset')], default='not mentioned', max_length=60),
        ),
        migrations.AddField(
            model_name='visitor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='exhibition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exhibitions.exhibition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='product_request',
            field=models.CharField(blank=True, choices=[('vaccumed vac', 'Vacuum Therapy'), ('vacumed vac Hyper', 'Hyper'), ('vacumed vac Hypermid', 'Hypermid'), ('canister', 'Canister'), ('dressing kit', 'Dressing Kit'), ('microderm abrasion', 'Microderm'), ('micro pigmentation', 'Micropigmentation'), ('miconeedling', 'Microneedling'), ('microderm probes', 'Probe'), ('microderm lifting probes', 'Lifting Probe'), ('Micropigmentation cartridges', 'P1 Cartridges'), ('Microneddling cartridges', 'P2 Cartridges'), ('not mentioned', 'Notset')], default='not mentioned', max_length=70),
        ),
        migrations.AddField(
            model_name='visitor',
            name='slaes_opinion',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='state',
            field=models.CharField(blank=True, default='Isfahan', max_length=30),
        ),
    ]
