# Generated by Django 3.2.9 on 2021-12-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0004_auto_20211205_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='form_header',
            field=models.TextField(blank=True, default='با تشکر از حضور جنابعالی در غرفه شرکت فنی مهندسی فناور پویا سپاهان. خواهشمند است نسبت به تکمیل فرم و اعلام درخواست اقدام فرمایید'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='exhibition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='exhibitions.exhibition'),
        ),
    ]
