# Generated by Django 3.2.9 on 2021-12-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0005_auto_20211205_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
