# Generated by Django 3.2.9 on 2021-12-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0006_exhibition_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='coop_request',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='product_request',
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=40)),
                ('visitor', models.ManyToManyField(related_name='products_request', to='exhibitions.Visitor')),
            ],
        ),
        migrations.CreateModel(
            name='CoopRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=40)),
                ('visitor', models.ManyToManyField(related_name='coop_request', to='exhibitions.Visitor')),
            ],
        ),
    ]
