# Generated by Django 3.2.9 on 2021-12-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0008_auto_20211211_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='phone_nunmber',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='cooprequest',
            name='visitor',
            field=models.ManyToManyField(related_name='coop_request', to='exhibitions.Visitor'),
        ),
        migrations.AlterField(
            model_name='products',
            name='visitor',
            field=models.ManyToManyField(related_name='products_request', to='exhibitions.Visitor'),
        ),
    ]
